In [1]:
import tensorflow as tf 

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.43955135,  0.12210823,  0.08128173,  0.37150052, -0.24309513,
         0.13190293, -0.26575407, -0.50025374, -0.21664558, -0.28824395]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.15413041, 0.1122082 , 0.10771938, 0.14399064, 0.07787871,
        0.11331265, 0.0761339 , 0.06021937, 0.07996605, 0.07444077]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.1776047

In [8]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


1875/1875 [==============================] - 5s 2ms/step - loss: 0.2962 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1435 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1081 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0860 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0752 - accuracy: 0.9760


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0776 - accuracy: 0.9754 - 662ms/epoch - 2ms/step


[0.07763376832008362, 0.9753999710083008]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.3129839e-10, 1.4395826e-10, 1.6238131e-07, 2.8893845e-05,
        9.7678636e-12, 3.2587266e-08, 5.5432508e-15, 9.9996889e-01,
        1.2507401e-07, 1.9469087e-06],
       [1.4129909e-08, 2.0868836e-04, 9.9977881e-01, 1.1892548e-05,
        3.8318828e-17, 5.1534028e-07, 3.0579701e-09, 8.0251561e-14,
        8.8751747e-08, 5.4234683e-14],
       [8.5566967e-07, 9.9611723e-01, 7.1644368e-05, 4.4343128e-06,
        1.4727407e-05, 1.9846944e-05, 4.2172986e-05, 3.2635019e-03,
        4.6414338e-04, 1.5629716e-06],
       [9.9962032e-01, 3.2536458e-09, 1.7091027e-04, 6.3817524e-08,
        8.6371170e-07, 2.5451287e-05, 1.7615912e-05, 1.2553121e-04,
        2.7253463e-08, 3.9214145e-05],
       [2.5081113e-06, 2.5250082e-09, 4.3414395e-05, 1.4608845e-07,
        9.9497932e-01, 1.7296166e-07, 1.1616687e-06, 5.9896665e-05,
        1.0892487e-06, 4.9122735e-03]], dtype=float32)>